services:
  #port 80
  nginx:
    build:
      context: ./Dockerfiles
      dockerfile: nginx
    container_name: nginx
    restart: always
    network_mode: host
    volumes:
      - ./Projects/app.boomsistemas.com.br:/var/www/app.boomsistemas.com.br
      - ./FilesConfigs/Nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  #port 7001
  php7:
    build:
      context: ./Dockerfiles
      dockerfile: php7
    image: brunojoao3/boom_docker_stack:php7-prod
    user: "root"
    container_name: php7
    restart: always
    network_mode: host
    volumes:
      - ./Projects/app.boomsistemas.com.br:/var/www/app.boomsistemas.com.br
      - ./FilesConfigs/Php7/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./FilesConfigs/Php7/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./FilesConfigs/Php7/www.conf.default:/usr/local/etc/php-fpm.d/www.conf.default
      - ./FilesConfigs/Php7/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    command: bash -c "chown -R www-data:1000 /var/www && chmod -R 775 /var/www && php-fpm"

